/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/ui/Alert.vue')['default']
    AuditReport: typeof import('./components/AuditReport.vue')['default']
    Badge: typeof import('./components/ui/Badge.vue')['default']
    Button: typeof import('./components/ui/Button.vue')['default']
    Card: typeof import('./components/ui/Card.vue')['default']
    CurrentTask: typeof import('./components/CurrentTask.vue')['default']
    DefaultLayout: typeof import('./components/layouts/DefaultLayout.vue')['default']
    Icon: typeof import('./components/ui/Icon.vue')['default']
    Input: typeof import('./components/ui/Input.vue')['default']
    LogFilters: typeof import('./components/logs/LogFilters.vue')['default']
    LogLine: typeof import('./components/logs/LogLine.vue')['default']
    LogStats: typeof import('./components/logs/LogStats.vue')['default']
    LogViewer: typeof import('./components/logs/LogViewer.vue')['default']
    PackageDownload: typeof import('./components/PackageDownload.vue')['default']
    Popconfirm: typeof import('./components/ui/Popconfirm.vue')['default']
    Popover: typeof import('./components/ui/Popover.vue')['default']
    Progress: typeof import('./components/ui/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectMenu: typeof import('./components/ui/SelectMenu.vue')['default']
    TaskCard: typeof import('./components/TaskCard.vue')['default']
    TaskHistory: typeof import('./components/TaskHistory.vue')['default']
    Toggle: typeof import('./components/ui/Toggle.vue')['default']
    UploadPanel: typeof import('./components/UploadPanel.vue')['default']
  }
}
